export const COUNTRIES = [
  { name: 'France', flag: '🇫🇷' },
  { name: 'Spain', flag: '🇪🇸' },
  { name: 'Argentina', flag: '🇦🇷' },
  { name: 'England', flag: '🇬🇧' },
  { name: 'Portugal', flag: '🇵🇹' },
  { name: 'Brazil', flag: '🇧🇷' },
  { name: 'Netherlands', flag: '🇳🇱' },
  { name: 'Morocco', flag: '🇲🇦' },
  { name: 'Belgium', flag: '🇧🇪' },
  { name: 'Germany', flag: '🇩🇪' },
  { name: 'Croatia', flag: '🇭🇷' },
  { name: 'Colombia', flag: '🇨🇴' },
  { name: 'Senegal', flag: '🇸🇳' },
  { name: 'Mexico', flag: '🇲🇽' },
  { name: 'United States', flag: '🇺🇸' },
  { name: 'Uruguay', flag: '🇺🇾' },
  { name: 'Japan', flag: '🇯🇵' },
  { name: 'Switzerland', flag: '🇨🇭' },
  { name: 'Iran', flag: '🇮🇷' },
  { name: 'Austria', flag: '🇦🇹' },
  { name: 'South Korea', flag: '🇰🇷' },
  { name: 'Chingoo United', flag: '👑' },
];

export const PLAYERS = [
  // --- CHINGOO UNITED CORE PRO CLUBS SQUAD ---
  {
    id: 'cu_1',
    name: 'Gringonator',
    ovr: 10,
    pos: 'Goalkeeper',
    country: 'Chingoo United',
    traitType: 'WILDCARD',
  },
  {
    id: 'cu_2',
    name: 'OllieTheDoodle',
    ovr: 85,
    pos: 'Defender',
    country: 'Chingoo United',
    traitType: 'WILDCARD',
  },
  {
    id: 'cu_3',
    name: 'DougDimadome322',
    ovr: 85,
    pos: 'Defender',
    country: 'Chingoo United',
    traitType: 'CATALYST',
  },
  {
    id: 'cu_4',
    name: 'Boston_Ramos26',
    ovr: 85,
    pos: 'Defender',
    country: 'Chingoo United',
    traitType: 'VETERAN',
  },
  {
    id: 'cu_5',
    name: 'lilYoun9',
    ovr: 85,
    pos: 'Midfielder',
    country: 'Chingoo United',
    traitType: 'WILDCARD',
  },
  {
    id: 'cu_6',
    name: 'joezhai12',
    ovr: 85,
    pos: 'Midfielder',
    country: 'Chingoo United',
    traitType: 'VETERAN',
  },
  {
    id: 'cu_7',
    name: 'gengho',
    ovr: 85,
    pos: 'Midfielder',
    country: 'Chingoo United',
    traitType: 'WONDERKID',
  },
  {
    id: 'cu_8',
    name: 'sailordooooom',
    ovr: 85,
    pos: 'Forward',
    country: 'Chingoo United',
    traitType: 'WONDERKID',
  },
  {
    id: 'cu_9',
    name: 'SongEC',
    ovr: 85,
    pos: 'Forward',
    country: 'Chingoo United',
    traitType: 'WILDCARD',
  },
  {
    id: 'cu_10',
    name: 'calamari1',
    ovr: 90,
    pos: 'Forward',
    country: 'Chingoo United',
    traitType: 'PRIMA_DONNA',
  },

  // --- FRANCE ---
  {
    id: 'fr_1',
    name: 'Mike Maignan',
    ovr: 87,
    pos: 'Goalkeeper',
    country: 'France',
    traitType: 'PRIMA_DONNA',
  },
  {
    id: 'fr_2',
    name: 'William Saliba',
    ovr: 87,
    pos: 'Defender',
    country: 'France',
    traitType: 'PRIMA_DONNA',
  },
  {
    id: 'fr_3',
    name: 'Ibrahima Konaté',
    ovr: 85,
    pos: 'Defender',
    country: 'France',
    traitType: 'CATALYST',
  },
  {
    id: 'fr_4',
    name: 'Jules Koundé',
    ovr: 87,
    pos: 'Defender',
    country: 'France',
    traitType: 'WILDCARD',
  },
  {
    id: 'fr_5',
    name: 'Aurélien Tchouaméni',
    ovr: 84,
    pos: 'Midfielder',
    country: 'France',
    traitType: 'VETERAN',
  },
  {
    id: 'fr_6',
    name: "N'Golo Kanté",
    ovr: 85,
    pos: 'Midfielder',
    country: 'France',
    traitType: 'CATALYST',
  },
  {
    id: 'fr_7',
    name: 'Adrien Rabiot',
    ovr: 84,
    pos: 'Midfielder',
    country: 'France',
    traitType: 'WONDERKID',
  },
  {
    id: 'fr_8',
    name: 'Kylian Mbappé',
    ovr: 91,
    pos: 'Forward',
    country: 'France',
    traitType: 'PRIMA_DONNA',
  },
  {
    id: 'fr_9',
    name: 'Ousmane Dembélé',
    ovr: 90,
    pos: 'Forward',
    country: 'France',
    traitType: 'WILDCARD',
  },
  {
    id: 'fr_10',
    name: 'Marcus Thuram',
    ovr: 85,
    pos: 'Forward',
    country: 'France',
    traitType: 'WONDERKID',
  },

  // --- SPAIN ---
  {
    id: 'es_1',
    name: 'Unai Simón',
    ovr: 85,
    pos: 'Goalkeeper',
    country: 'Spain',
    traitType: 'WILDCARD',
  },
  {
    id: 'es_2',
    name: 'Dani Carvajal',
    ovr: 85,
    pos: 'Defender',
    country: 'Spain',
    traitType: 'VETERAN',
  },
  {
    id: 'es_3',
    name: 'Íñigo Martínez',
    ovr: 85,
    pos: 'Defender',
    country: 'Spain',
    traitType: 'CATALYST',
  },
  {
    id: 'es_4',
    name: 'Marc Cucurella',
    ovr: 84,
    pos: 'Defender',
    country: 'Spain',
    traitType: 'WONDERKID',
  },
  {
    id: 'es_5',
    name: 'Rodri',
    ovr: 90,
    pos: 'Midfielder',
    country: 'Spain',
    traitType: 'PRIMA_DONNA',
  },
  {
    id: 'es_6',
    name: 'Pedri',
    ovr: 89,
    pos: 'Midfielder',
    country: 'Spain',
    traitType: 'WONDERKID',
  },
  {
    id: 'es_7',
    name: 'Dani Olmo',
    ovr: 85,
    pos: 'Midfielder',
    country: 'Spain',
    traitType: 'CATALYST',
  },
  {
    id: 'es_8',
    name: 'Lamine Yamal',
    ovr: 89,
    pos: 'Forward',
    country: 'Spain',
    traitType: 'PRIMA_DONNA',
  },
  {
    id: 'es_9',
    name: 'Nico Williams',
    ovr: 86,
    pos: 'Forward',
    country: 'Spain',
    traitType: 'WILDCARD',
  },
  {
    id: 'es_10',
    name: 'Mikel Oyarzabal',
    ovr: 84,
    pos: 'Forward',
    country: 'Spain',
    traitType: 'WONDERKID',
  },

  // --- ARGENTINA ---
  {
    id: 'ar_1',
    name: 'Emiliano Martínez',
    ovr: 85,
    pos: 'Goalkeeper',
    country: 'Argentina',
    traitType: 'WILDCARD',
  },
  {
    id: 'ar_2',
    name: 'Cristian Romero',
    ovr: 84,
    pos: 'Defender',
    country: 'Argentina',
    traitType: 'WILDCARD',
  },
  {
    id: 'ar_3',
    name: 'Nicolás Otamendi',
    ovr: 82,
    pos: 'Defender',
    country: 'Argentina',
    traitType: 'VETERAN',
  },
  {
    id: 'ar_4',
    name: 'Nahuel Molina',
    ovr: 81,
    pos: 'Defender',
    country: 'Argentina',
    traitType: 'CATALYST',
  },
  {
    id: 'ar_5',
    name: 'Alexis Mac Allister',
    ovr: 87,
    pos: 'Midfielder',
    country: 'Argentina',
    traitType: 'PRIMA_DONNA',
  },
  {
    id: 'ar_6',
    name: 'Rodrigo De Paul',
    ovr: 84,
    pos: 'Midfielder',
    country: 'Argentina',
    traitType: 'WILDCARD',
  },
  {
    id: 'ar_7',
    name: 'Enzo Fernández',
    ovr: 84,
    pos: 'Midfielder',
    country: 'Argentina',
    traitType: 'CATALYST',
  },
  {
    id: 'ar_8',
    name: 'Lautaro Martínez',
    ovr: 88,
    pos: 'Forward',
    country: 'Argentina',
    traitType: 'PRIMA_DONNA',
  },
  {
    id: 'ar_9',
    name: 'Julián Álvarez',
    ovr: 87,
    pos: 'Forward',
    country: 'Argentina',
    traitType: 'WONDERKID',
  },
  {
    id: 'ar_10',
    name: 'Lionel Messi',
    ovr: 86,
    pos: 'Forward',
    country: 'Argentina',
    traitType: 'VETERAN',
  },

  // --- ENGLAND ---
  {
    id: 'en_1',
    name: 'Jordan Pickford',
    ovr: 84,
    pos: 'Goalkeeper',
    country: 'England',
    traitType: 'WILDCARD',
  },
  {
    id: 'en_2',
    name: 'Trent Alexander-Arnold',
    ovr: 86,
    pos: 'Defender',
    country: 'England',
    traitType: 'WILDCARD',
  },
  {
    id: 'en_3',
    name: 'John Stones',
    ovr: 84,
    pos: 'Defender',
    country: 'England',
    traitType: 'VETERAN',
  },
  {
    id: 'en_4',
    name: 'Marc Guéhi',
    ovr: 82,
    pos: 'Defender',
    country: 'England',
    traitType: 'WONDERKID',
  },
  {
    id: 'en_5',
    name: 'Jude Bellingham',
    ovr: 90,
    pos: 'Midfielder',
    country: 'England',
    traitType: 'PRIMA_DONNA',
  },
  {
    id: 'en_6',
    name: 'Declan Rice',
    ovr: 87,
    pos: 'Midfielder',
    country: 'England',
    traitType: 'CATALYST',
  },
  {
    id: 'en_7',
    name: 'Cole Palmer',
    ovr: 87,
    pos: 'Midfielder',
    country: 'England',
    traitType: 'WILDCARD',
  },
  {
    id: 'en_8',
    name: 'Harry Kane',
    ovr: 89,
    pos: 'Forward',
    country: 'England',
    traitType: 'PRIMA_DONNA',
  },
  {
    id: 'en_9',
    name: 'Bukayo Saka',
    ovr: 88,
    pos: 'Forward',
    country: 'England',
    traitType: 'WONDERKID',
  },
  {
    id: 'en_10',
    name: 'Phil Foden',
    ovr: 85,
    pos: 'Forward',
    country: 'England',
    traitType: 'CATALYST',
  },

  // --- PORTUGAL ---
  {
    id: 'pt_1',
    name: 'Diogo Costa',
    ovr: 85,
    pos: 'Goalkeeper',
    country: 'Portugal',
    traitType: 'CATALYST',
  },
  {
    id: 'pt_2',
    name: 'Rúben Dias',
    ovr: 86,
    pos: 'Defender',
    country: 'Portugal',
    traitType: 'VETERAN',
  },
  {
    id: 'pt_3',
    name: 'Nuno Mendes',
    ovr: 86,
    pos: 'Defender',
    country: 'Portugal',
    traitType: 'WONDERKID',
  },
  {
    id: 'pt_4',
    name: 'João Cancelo',
    ovr: 84,
    pos: 'Defender',
    country: 'Portugal',
    traitType: 'CATALYST',
  },
  {
    id: 'pt_5',
    name: 'Vitinha',
    ovr: 89,
    pos: 'Midfielder',
    country: 'Portugal',
    traitType: 'PRIMA_DONNA',
  },
  {
    id: 'pt_6',
    name: 'Bruno Fernandes',
    ovr: 87,
    pos: 'Midfielder',
    country: 'Portugal',
    traitType: 'WILDCARD',
  },
  {
    id: 'pt_7',
    name: 'João Neves',
    ovr: 85,
    pos: 'Midfielder',
    country: 'Portugal',
    traitType: 'WONDERKID',
  },
  {
    id: 'pt_8',
    name: 'Cristiano Ronaldo',
    ovr: 85,
    pos: 'Forward',
    country: 'Portugal',
    traitType: 'VETERAN',
  },
  {
    id: 'pt_9',
    name: 'Rafael Leão',
    ovr: 84,
    pos: 'Forward',
    country: 'Portugal',
    traitType: 'WILDCARD',
  },
  {
    id: 'pt_10',
    name: 'Pedro Neto',
    ovr: 82,
    pos: 'Forward',
    country: 'Portugal',
    traitType: 'CATALYST',
  },

  // --- BRAZIL ---
  {
    id: 'br_1',
    name: 'Alisson',
    ovr: 89,
    pos: 'Goalkeeper',
    country: 'Brazil',
    traitType: 'PRIMA_DONNA',
  },
  {
    id: 'br_2',
    name: 'Gabriel Magalhães',
    ovr: 88,
    pos: 'Defender',
    country: 'Brazil',
    traitType: 'PRIMA_DONNA',
  },
  {
    id: 'br_3',
    name: 'Marquinhos',
    ovr: 87,
    pos: 'Defender',
    country: 'Brazil',
    traitType: 'VETERAN',
  },
  {
    id: 'br_4',
    name: 'Bremer',
    ovr: 85,
    pos: 'Defender',
    country: 'Brazil',
    traitType: 'CATALYST',
  },
  {
    id: 'br_5',
    name: 'Bruno Guimarães',
    ovr: 86,
    pos: 'Midfielder',
    country: 'Brazil',
    traitType: 'CATALYST',
  },
  {
    id: 'br_6',
    name: 'Lucas Paquetá',
    ovr: 83,
    pos: 'Midfielder',
    country: 'Brazil',
    traitType: 'WILDCARD',
  },
  {
    id: 'br_7',
    name: 'Casemiro',
    ovr: 83,
    pos: 'Midfielder',
    country: 'Brazil',
    traitType: 'VETERAN',
  },
  {
    id: 'br_8',
    name: 'Raphinha',
    ovr: 89,
    pos: 'Forward',
    country: 'Brazil',
    traitType: 'PRIMA_DONNA',
  },
  {
    id: 'br_9',
    name: 'Vinícius Jr',
    ovr: 89,
    pos: 'Forward',
    country: 'Brazil',
    traitType: 'WILDCARD',
  },
  {
    id: 'br_10',
    name: 'Rodrygo',
    ovr: 85,
    pos: 'Forward',
    country: 'Brazil',
    traitType: 'WONDERKID',
  },

  // --- NETHERLANDS ---
  {
    id: 'nl_1',
    name: 'Bart Verbruggen',
    ovr: 82,
    pos: 'Goalkeeper',
    country: 'Netherlands',
    traitType: 'WONDERKID',
  },
  {
    id: 'nl_2',
    name: 'Virgil van Dijk',
    ovr: 90,
    pos: 'Defender',
    country: 'Netherlands',
    traitType: 'PRIMA_DONNA',
  },
  {
    id: 'nl_3',
    name: 'Denzel Dumfries',
    ovr: 83,
    pos: 'Defender',
    country: 'Netherlands',
    traitType: 'WILDCARD',
  },
  {
    id: 'nl_4',
    name: 'Micky van de Ven',
    ovr: 83,
    pos: 'Defender',
    country: 'Netherlands',
    traitType: 'CATALYST',
  },
  {
    id: 'nl_5',
    name: 'Frenkie de Jong',
    ovr: 87,
    pos: 'Midfielder',
    country: 'Netherlands',
    traitType: 'VETERAN',
  },
  {
    id: 'nl_6',
    name: 'Ryan Gravenberch',
    ovr: 85,
    pos: 'Midfielder',
    country: 'Netherlands',
    traitType: 'CATALYST',
  },
  {
    id: 'nl_7',
    name: 'Tijjani Reijnders',
    ovr: 84,
    pos: 'Midfielder',
    country: 'Netherlands',
    traitType: 'WONDERKID',
  },
  {
    id: 'nl_8',
    name: 'Cody Gakpo',
    ovr: 84,
    pos: 'Forward',
    country: 'Netherlands',
    traitType: 'WONDERKID',
  },
  {
    id: 'nl_9',
    name: 'Memphis Depay',
    ovr: 83,
    pos: 'Forward',
    country: 'Netherlands',
    traitType: 'WILDCARD',
  },
  {
    id: 'nl_10',
    name: 'Xavi Simons',
    ovr: 84,
    pos: 'Forward',
    country: 'Netherlands',
    traitType: 'CATALYST',
  },

  // --- MOROCCO ---
  {
    id: 'ma_1',
    name: 'Yassine Bounou',
    ovr: 84,
    pos: 'Goalkeeper',
    country: 'Morocco',
    traitType: 'VETERAN',
  },
  {
    id: 'ma_2',
    name: 'Achraf Hakimi',
    ovr: 89,
    pos: 'Defender',
    country: 'Morocco',
    traitType: 'PRIMA_DONNA',
  },
  {
    id: 'ma_3',
    name: 'Noussair Mazraoui',
    ovr: 80,
    pos: 'Defender',
    country: 'Morocco',
    traitType: 'CATALYST',
  },
  {
    id: 'ma_4',
    name: 'Nayef Aguerd',
    ovr: 79,
    pos: 'Defender',
    country: 'Morocco',
    traitType: 'WILDCARD',
  },
  {
    id: 'ma_5',
    name: 'Sofyan Amrabat',
    ovr: 78,
    pos: 'Midfielder',
    country: 'Morocco',
    traitType: 'VETERAN',
  },
  {
    id: 'ma_6',
    name: 'Ismael Saibari',
    ovr: 79,
    pos: 'Midfielder',
    country: 'Morocco',
    traitType: 'CATALYST',
  },
  {
    id: 'ma_7',
    name: 'Azzedine Ounahi',
    ovr: 76,
    pos: 'Midfielder',
    country: 'Morocco',
    traitType: 'WONDERKID',
  },
  {
    id: 'ma_8',
    name: 'Brahim Díaz',
    ovr: 82,
    pos: 'Forward',
    country: 'Morocco',
    traitType: 'WILDCARD',
  },
  {
    id: 'ma_9',
    name: 'Amine Adli',
    ovr: 78,
    pos: 'Forward',
    country: 'Morocco',
    traitType: 'WONDERKID',
  },
  {
    id: 'ma_10',
    name: 'Soufiane Rahimi',
    ovr: 78,
    pos: 'Forward',
    country: 'Morocco',
    traitType: 'CATALYST',
  },

  // --- BELGIUM ---
  {
    id: 'be_1',
    name: 'Thibaut Courtois',
    ovr: 89,
    pos: 'Goalkeeper',
    country: 'Belgium',
    traitType: 'PRIMA_DONNA',
  },
  {
    id: 'be_2',
    name: 'Wout Faes',
    ovr: 80,
    pos: 'Defender',
    country: 'Belgium',
    traitType: 'WILDCARD',
  },
  {
    id: 'be_3',
    name: 'Zeno Debast',
    ovr: 79,
    pos: 'Defender',
    country: 'Belgium',
    traitType: 'WONDERKID',
  },
  {
    id: 'be_4',
    name: 'Timothy Castagne',
    ovr: 79,
    pos: 'Defender',
    country: 'Belgium',
    traitType: 'CATALYST',
  },
  {
    id: 'be_5',
    name: 'Kevin De Bruyne',
    ovr: 87,
    pos: 'Midfielder',
    country: 'Belgium',
    traitType: 'PRIMA_DONNA',
  },
  {
    id: 'be_6',
    name: 'Youri Tielemans',
    ovr: 85,
    pos: 'Midfielder',
    country: 'Belgium',
    traitType: 'VETERAN',
  },
  {
    id: 'be_7',
    name: 'Amadou Onana',
    ovr: 82,
    pos: 'Midfielder',
    country: 'Belgium',
    traitType: 'CATALYST',
  },
  {
    id: 'be_8',
    name: 'Romelu Lukaku',
    ovr: 84,
    pos: 'Forward',
    country: 'Belgium',
    traitType: 'VETERAN',
  },
  {
    id: 'be_9',
    name: 'Jérémie Doku',
    ovr: 83,
    pos: 'Forward',
    country: 'Belgium',
    traitType: 'WILDCARD',
  },
  {
    id: 'be_10',
    name: 'Leandro Trossard',
    ovr: 83,
    pos: 'Forward',
    country: 'Belgium',
    traitType: 'WONDERKID',
  },

  // --- GERMANY ---
  {
    id: 'de_1',
    name: 'Marc-André ter Stegen',
    ovr: 86,
    pos: 'Goalkeeper',
    country: 'Germany',
    traitType: 'VETERAN',
  },
  {
    id: 'de_2',
    name: 'Antonio Rüdiger',
    ovr: 86,
    pos: 'Defender',
    country: 'Germany',
    traitType: 'VETERAN',
  },
  {
    id: 'de_3',
    name: 'Jonathan Tah',
    ovr: 87,
    pos: 'Defender',
    country: 'Germany',
    traitType: 'PRIMA_DONNA',
  },
  {
    id: 'de_4',
    name: 'Nico Schlotterbeck',
    ovr: 85,
    pos: 'Defender',
    country: 'Germany',
    traitType: 'CATALYST',
  },
  {
    id: 'de_5',
    name: 'Joshua Kimmich',
    ovr: 89,
    pos: 'Midfielder',
    country: 'Germany',
    traitType: 'PRIMA_DONNA',
  },
  {
    id: 'de_6',
    name: 'Florian Wirtz',
    ovr: 89,
    pos: 'Midfielder',
    country: 'Germany',
    traitType: 'WILDCARD',
  },
  {
    id: 'de_7',
    name: 'Jamal Musiala',
    ovr: 88,
    pos: 'Midfielder',
    country: 'Germany',
    traitType: 'WONDERKID',
  },
  {
    id: 'de_8',
    name: 'Kai Havertz',
    ovr: 84,
    pos: 'Forward',
    country: 'Germany',
    traitType: 'VETERAN',
  },
  {
    id: 'de_9',
    name: 'Serge Gnabry',
    ovr: 83,
    pos: 'Forward',
    country: 'Germany',
    traitType: 'WILDCARD',
  },
  {
    id: 'de_10',
    name: 'Leroy Sané',
    ovr: 83,
    pos: 'Forward',
    country: 'Germany',
    traitType: 'CATALYST',
  },

  // --- CROATIA ---
  {
    id: 'hr_1',
    name: 'Dominik Livaković',
    ovr: 82,
    pos: 'Goalkeeper',
    country: 'Croatia',
    traitType: 'CATALYST',
  },
  {
    id: 'hr_2',
    name: 'Joško Gvardiol',
    ovr: 84,
    pos: 'Defender',
    country: 'Croatia',
    traitType: 'VETERAN',
  },
  {
    id: 'hr_3',
    name: 'Joško Šutalo',
    ovr: 78,
    pos: 'Defender',
    country: 'Croatia',
    traitType: 'WONDERKID',
  },
  {
    id: 'hr_4',
    name: 'Josip Stanišić',
    ovr: 80,
    pos: 'Defender',
    country: 'Croatia',
    traitType: 'CATALYST',
  },
  {
    id: 'hr_5',
    name: 'Luka Modrić',
    ovr: 84,
    pos: 'Midfielder',
    country: 'Croatia',
    traitType: 'VETERAN',
  },
  {
    id: 'hr_6',
    name: 'Mateo Kovačić',
    ovr: 84,
    pos: 'Midfielder',
    country: 'Croatia',
    traitType: 'CATALYST',
  },
  {
    id: 'hr_7',
    name: 'Marcelo Brozović',
    ovr: 82,
    pos: 'Midfielder',
    country: 'Croatia',
    traitType: 'WILDCARD',
  },
  {
    id: 'hr_8',
    name: 'Andrej Kramarić',
    ovr: 81,
    pos: 'Forward',
    country: 'Croatia',
    traitType: 'WILDCARD',
  },
  {
    id: 'hr_9',
    name: 'Ante Budimir',
    ovr: 80,
    pos: 'Forward',
    country: 'Croatia',
    traitType: 'VETERAN',
  },
  {
    id: 'hr_10',
    name: 'Igor Matanović',
    ovr: 75,
    pos: 'Forward',
    country: 'Croatia',
    traitType: 'WONDERKID',
  },

  // --- COLOMBIA ---
  {
    id: 'co_1',
    name: 'Camilo Vargas',
    ovr: 79,
    pos: 'Goalkeeper',
    country: 'Colombia',
    traitType: 'VETERAN',
  },
  {
    id: 'co_2',
    name: 'Dávinson Sánchez',
    ovr: 81,
    pos: 'Defender',
    country: 'Colombia',
    traitType: 'VETERAN',
  },
  {
    id: 'co_3',
    name: 'Daniel Muñoz',
    ovr: 81,
    pos: 'Defender',
    country: 'Colombia',
    traitType: 'WILDCARD',
  },
  {
    id: 'co_4',
    name: 'Jhon Lucumí',
    ovr: 80,
    pos: 'Defender',
    country: 'Colombia',
    traitType: 'CATALYST',
  },
  {
    id: 'co_5',
    name: 'James Rodríguez',
    ovr: 82,
    pos: 'Midfielder',
    country: 'Colombia',
    traitType: 'WILDCARD',
  },
  {
    id: 'co_6',
    name: 'Richard Ríos',
    ovr: 81,
    pos: 'Midfielder',
    country: 'Colombia',
    traitType: 'WONDERKID',
  },
  {
    id: 'co_7',
    name: 'Jefferson Lerma',
    ovr: 80,
    pos: 'Midfielder',
    country: 'Colombia',
    traitType: 'CATALYST',
  },
  {
    id: 'co_8',
    name: 'Luis Díaz',
    ovr: 85,
    pos: 'Forward',
    country: 'Colombia',
    traitType: 'WILDCARD',
  },
  {
    id: 'co_9',
    name: 'Jhon Durán',
    ovr: 81,
    pos: 'Forward',
    country: 'Colombia',
    traitType: 'WONDERKID',
  },
  {
    id: 'co_10',
    name: 'Rafael Santos Borré',
    ovr: 78,
    pos: 'Forward',
    country: 'Colombia',
    traitType: 'CATALYST',
  },

  // --- SENEGAL ---
  {
    id: 'sn_1',
    name: 'Édouard Mendy',
    ovr: 83,
    pos: 'Goalkeeper',
    country: 'Senegal',
    traitType: 'VETERAN',
  },
  {
    id: 'sn_2',
    name: 'Kalidou Koulibaly',
    ovr: 82,
    pos: 'Defender',
    country: 'Senegal',
    traitType: 'VETERAN',
  },
  {
    id: 'sn_3',
    name: 'Abdou Diallo',
    ovr: 79,
    pos: 'Defender',
    country: 'Senegal',
    traitType: 'CATALYST',
  },
  {
    id: 'sn_4',
    name: 'Ismail Jakobs',
    ovr: 78,
    pos: 'Defender',
    country: 'Senegal',
    traitType: 'WONDERKID',
  },
  {
    id: 'sn_5',
    name: 'Pape Matar Sarr',
    ovr: 81,
    pos: 'Midfielder',
    country: 'Senegal',
    traitType: 'WONDERKID',
  },
  {
    id: 'sn_6',
    name: 'Idrissa Gueye',
    ovr: 80,
    pos: 'Midfielder',
    country: 'Senegal',
    traitType: 'VETERAN',
  },
  {
    id: 'sn_7',
    name: 'Pape Gueye',
    ovr: 78,
    pos: 'Midfielder',
    country: 'Senegal',
    traitType: 'CATALYST',
  },
  {
    id: 'sn_8',
    name: 'Nicolas Jackson',
    ovr: 82,
    pos: 'Forward',
    country: 'Senegal',
    traitType: 'WILDCARD',
  },
  {
    id: 'sn_9',
    name: 'Iliman Ndiaye',
    ovr: 80,
    pos: 'Forward',
    country: 'Senegal',
    traitType: 'WONDERKID',
  },
  {
    id: 'sn_10',
    name: 'Ismaïla Sarr',
    ovr: 80,
    pos: 'Forward',
    country: 'Senegal',
    traitType: 'CATALYST',
  },

  // --- MEXICO ---
  {
    id: 'mx_1',
    name: 'Guillermo Ochoa',
    ovr: 79,
    pos: 'Goalkeeper',
    country: 'Mexico',
    traitType: 'VETERAN',
  },
  {
    id: 'mx_2',
    name: 'César Montes',
    ovr: 79,
    pos: 'Defender',
    country: 'Mexico',
    traitType: 'VETERAN',
  },
  {
    id: 'mx_3',
    name: 'Johan Vásquez',
    ovr: 79,
    pos: 'Defender',
    country: 'Mexico',
    traitType: 'CATALYST',
  },
  {
    id: 'mx_4',
    name: 'Jorge Sánchez',
    ovr: 76,
    pos: 'Defender',
    country: 'Mexico',
    traitType: 'WONDERKID',
  },
  {
    id: 'mx_5',
    name: 'Edson Álvarez',
    ovr: 82,
    pos: 'Midfielder',
    country: 'Mexico',
    traitType: 'VETERAN',
  },
  {
    id: 'mx_6',
    name: 'Luis Chávez',
    ovr: 79,
    pos: 'Midfielder',
    country: 'Mexico',
    traitType: 'CATALYST',
  },
  {
    id: 'mx_7',
    name: 'Orbelín Pineda',
    ovr: 78,
    pos: 'Midfielder',
    country: 'Mexico',
    traitType: 'WILDCARD',
  },
  {
    id: 'mx_8',
    name: 'Santiago Giménez',
    ovr: 81,
    pos: 'Forward',
    country: 'Mexico',
    traitType: 'WONDERKID',
  },
  {
    id: 'mx_9',
    name: 'Raúl Jiménez',
    ovr: 79,
    pos: 'Forward',
    country: 'Mexico',
    traitType: 'WILDCARD',
  },
  {
    id: 'mx_10',
    name: 'Hirving Lozano',
    ovr: 81,
    pos: 'Forward',
    country: 'Mexico',
    traitType: 'CATALYST',
  },

  // --- UNITED STATES ---
  {
    id: 'us_1',
    name: 'Matt Turner',
    ovr: 79,
    pos: 'Goalkeeper',
    country: 'United States',
    traitType: 'CATALYST',
  },
  {
    id: 'us_2',
    name: 'Antonee Robinson',
    ovr: 81,
    pos: 'Defender',
    country: 'United States',
    traitType: 'WILDCARD',
  },
  {
    id: 'us_3',
    name: 'Chris Richards',
    ovr: 79,
    pos: 'Defender',
    country: 'United States',
    traitType: 'VETERAN',
  },
  {
    id: 'us_4',
    name: 'Sergiño Dest',
    ovr: 79,
    pos: 'Defender',
    country: 'United States',
    traitType: 'CATALYST',
  },
  {
    id: 'us_5',
    name: 'Weston McKennie',
    ovr: 81,
    pos: 'Midfielder',
    country: 'United States',
    traitType: 'WILDCARD',
  },
  {
    id: 'us_6',
    name: 'Tyler Adams',
    ovr: 80,
    pos: 'Midfielder',
    country: 'United States',
    traitType: 'VETERAN',
  },
  {
    id: 'us_7',
    name: 'Yunus Musah',
    ovr: 79,
    pos: 'Midfielder',
    country: 'United States',
    traitType: 'WONDERKID',
  },
  {
    id: 'us_8',
    name: 'Christian Pulisic',
    ovr: 84,
    pos: 'Forward',
    country: 'United States',
    traitType: 'WILDCARD',
  },
  {
    id: 'us_9',
    name: 'Folarin Balogun',
    ovr: 80,
    pos: 'Forward',
    country: 'United States',
    traitType: 'WONDERKID',
  },
  {
    id: 'us_10',
    name: 'Timothy Weah',
    ovr: 78,
    pos: 'Forward',
    country: 'United States',
    traitType: 'CATALYST',
  },

  // --- URUGUAY ---
  {
    id: 'uy_1',
    name: 'Sergio Rochet',
    ovr: 78,
    pos: 'Goalkeeper',
    country: 'Uruguay',
    traitType: 'VETERAN',
  },
  {
    id: 'uy_2',
    name: 'Ronald Araújo',
    ovr: 85,
    pos: 'Defender',
    country: 'Uruguay',
    traitType: 'WILDCARD',
  },
  {
    id: 'uy_3',
    name: 'José María Giménez',
    ovr: 83,
    pos: 'Defender',
    country: 'Uruguay',
    traitType: 'VETERAN',
  },
  {
    id: 'uy_4',
    name: 'Mathías Olivera',
    ovr: 80,
    pos: 'Defender',
    country: 'Uruguay',
    traitType: 'CATALYST',
  },
  {
    id: 'uy_5',
    name: 'Federico Valverde',
    ovr: 89,
    pos: 'Midfielder',
    country: 'Uruguay',
    traitType: 'PRIMA_DONNA',
  },
  {
    id: 'uy_6',
    name: 'Manuel Ugarte',
    ovr: 81,
    pos: 'Midfielder',
    country: 'Uruguay',
    traitType: 'CATALYST',
  },
  {
    id: 'uy_7',
    name: 'Nicolás de la Cruz',
    ovr: 81,
    pos: 'Midfielder',
    country: 'Uruguay',
    traitType: 'WILDCARD',
  },
  {
    id: 'uy_8',
    name: 'Darwin Núñez',
    ovr: 82,
    pos: 'Forward',
    country: 'Uruguay',
    traitType: 'WILDCARD',
  },
  {
    id: 'uy_9',
    name: 'Facundo Pellistri',
    ovr: 78,
    pos: 'Forward',
    country: 'Uruguay',
    traitType: 'WONDERKID',
  },
  {
    id: 'uy_10',
    name: 'Maxi Araújo',
    ovr: 77,
    pos: 'Forward',
    country: 'Uruguay',
    traitType: 'CATALYST',
  },

  // --- JAPAN ---
  {
    id: 'jp_1',
    name: 'Zion Suzuki',
    ovr: 79,
    pos: 'Goalkeeper',
    country: 'Japan',
    traitType: 'WONDERKID',
  },
  {
    id: 'jp_2',
    name: 'Ko Itakura',
    ovr: 80,
    pos: 'Defender',
    country: 'Japan',
    traitType: 'VETERAN',
  },
  {
    id: 'jp_3',
    name: 'Takehiro Tomiyasu',
    ovr: 80,
    pos: 'Defender',
    country: 'Japan',
    traitType: 'CATALYST',
  },
  {
    id: 'jp_4',
    name: 'Hiroki Itō',
    ovr: 79,
    pos: 'Defender',
    country: 'Japan',
    traitType: 'WONDERKID',
  },
  {
    id: 'jp_5',
    name: 'Wataru Endō',
    ovr: 81,
    pos: 'Midfielder',
    country: 'Japan',
    traitType: 'VETERAN',
  },
  {
    id: 'jp_6',
    name: 'Hidemasa Morita',
    ovr: 80,
    pos: 'Midfielder',
    country: 'Japan',
    traitType: 'CATALYST',
  },
  {
    id: 'jp_7',
    name: 'Takefusa Kubo',
    ovr: 82,
    pos: 'Midfielder',
    country: 'Japan',
    traitType: 'WILDCARD',
  },
  {
    id: 'jp_8',
    name: 'Kaoru Mitoma',
    ovr: 83,
    pos: 'Forward',
    country: 'Japan',
    traitType: 'WILDCARD',
  },
  {
    id: 'jp_9',
    name: 'Daizen Maeda',
    ovr: 80,
    pos: 'Forward',
    country: 'Japan',
    traitType: 'VETERAN',
  },
  {
    id: 'jp_10',
    name: 'Ayase Ueda',
    ovr: 79,
    pos: 'Forward',
    country: 'Japan',
    traitType: 'WONDERKID',
  },

  // --- SWITZERLAND ---
  {
    id: 'ch_1',
    name: 'Yann Sommer',
    ovr: 87,
    pos: 'Goalkeeper',
    country: 'Switzerland',
    traitType: 'PRIMA_DONNA',
  },
  {
    id: 'ch_2',
    name: 'Manuel Akanji',
    ovr: 84,
    pos: 'Defender',
    country: 'Switzerland',
    traitType: 'VETERAN',
  },
  {
    id: 'ch_3',
    name: 'Nico Elvedi',
    ovr: 80,
    pos: 'Defender',
    country: 'Switzerland',
    traitType: 'CATALYST',
  },
  {
    id: 'ch_4',
    name: 'Ricardo Rodríguez',
    ovr: 78,
    pos: 'Defender',
    country: 'Switzerland',
    traitType: 'WILDCARD',
  },
  {
    id: 'ch_5',
    name: 'Granit Xhaka',
    ovr: 85,
    pos: 'Midfielder',
    country: 'Switzerland',
    traitType: 'VETERAN',
  },
  {
    id: 'ch_6',
    name: 'Remo Freuler',
    ovr: 80,
    pos: 'Midfielder',
    country: 'Switzerland',
    traitType: 'CATALYST',
  },
  {
    id: 'ch_7',
    name: 'Michel Aebischer',
    ovr: 78,
    pos: 'Midfielder',
    country: 'Switzerland',
    traitType: 'WONDERKID',
  },
  {
    id: 'ch_8',
    name: 'Breel Embolo',
    ovr: 80,
    pos: 'Forward',
    country: 'Switzerland',
    traitType: 'WILDCARD',
  },
  {
    id: 'ch_9',
    name: 'Dan Ndoye',
    ovr: 80,
    pos: 'Forward',
    country: 'Switzerland',
    traitType: 'WONDERKID',
  },
  {
    id: 'ch_10',
    name: 'Ruben Vargas',
    ovr: 79,
    pos: 'Forward',
    country: 'Switzerland',
    traitType: 'CATALYST',
  },

  // --- IRAN ---
  {
    id: 'ir_1',
    name: 'Alireza Beiranvand',
    ovr: 76,
    pos: 'Goalkeeper',
    country: 'Iran',
    traitType: 'VETERAN',
  },
  {
    id: 'ir_2',
    name: 'Shojae Khalilzadeh',
    ovr: 74,
    pos: 'Defender',
    country: 'Iran',
    traitType: 'VETERAN',
  },
  {
    id: 'ir_3',
    name: 'Majid Hosseini',
    ovr: 73,
    pos: 'Defender',
    country: 'Iran',
    traitType: 'CATALYST',
  },
  {
    id: 'ir_4',
    name: 'Sadegh Moharrami',
    ovr: 72,
    pos: 'Defender',
    country: 'Iran',
    traitType: 'WONDERKID',
  },
  {
    id: 'ir_5',
    name: 'Saeid Ezatolahi',
    ovr: 74,
    pos: 'Midfielder',
    country: 'Iran',
    traitType: 'VETERAN',
  },
  {
    id: 'ir_6',
    name: 'Ali Karimi',
    ovr: 73,
    pos: 'Midfielder',
    country: 'Iran',
    traitType: 'CATALYST',
  },
  {
    id: 'ir_7',
    name: 'Alireza Jahanbakhsh',
    ovr: 76,
    pos: 'Midfielder',
    country: 'Iran',
    traitType: 'WILDCARD',
  },
  {
    id: 'ir_8',
    name: 'Mehdi Taremi',
    ovr: 80,
    pos: 'Forward',
    country: 'Iran',
    traitType: 'WILDCARD',
  },
  {
    id: 'ir_9',
    name: 'Sardar Azmoun',
    ovr: 78,
    pos: 'Forward',
    country: 'Iran',
    traitType: 'VETERAN',
  },
  {
    id: 'ir_10',
    name: 'Mehdi Ghayedi',
    ovr: 74,
    pos: 'Forward',
    country: 'Iran',
    traitType: 'WONDERKID',
  },

  // --- AUSTRIA ---
  {
    id: 'at_1',
    name: 'Patrick Pentz',
    ovr: 77,
    pos: 'Goalkeeper',
    country: 'Austria',
    traitType: 'WILDCARD',
  },
  {
    id: 'at_2',
    name: 'David Alaba',
    ovr: 83,
    pos: 'Defender',
    country: 'Austria',
    traitType: 'VETERAN',
  },
  {
    id: 'at_3',
    name: 'Kevin Danso',
    ovr: 80,
    pos: 'Defender',
    country: 'Austria',
    traitType: 'CATALYST',
  },
  {
    id: 'at_4',
    name: 'Philipp Mwene',
    ovr: 77,
    pos: 'Defender',
    country: 'Austria',
    traitType: 'WONDERKID',
  },
  {
    id: 'at_5',
    name: 'Konrad Laimer',
    ovr: 82,
    pos: 'Midfielder',
    country: 'Austria',
    traitType: 'WILDCARD',
  },
  {
    id: 'at_6',
    name: 'Nicolas Seiwald',
    ovr: 80,
    pos: 'Midfielder',
    country: 'Austria',
    traitType: 'CATALYST',
  },
  {
    id: 'at_7',
    name: 'Christoph Baumgartner',
    ovr: 81,
    pos: 'Midfielder',
    country: 'Austria',
    traitType: 'WONDERKID',
  },
  {
    id: 'at_8',
    name: 'Marko Arnautović',
    ovr: 79,
    pos: 'Forward',
    country: 'Austria',
    traitType: 'WILDCARD',
  },
  {
    id: 'at_9',
    name: 'Michael Gregoritsch',
    ovr: 78,
    pos: 'Forward',
    country: 'Austria',
    traitType: 'VETERAN',
  },
  {
    id: 'at_10',
    name: 'Marcel Sabitzer',
    ovr: 81,
    pos: 'Forward',
    country: 'Austria',
    traitType: 'CATALYST',
  },

  // --- SOUTH KOREA ---
  {
    id: 'kr_1',
    name: 'Kim Seung-gyu',
    ovr: 76,
    pos: 'Goalkeeper',
    country: 'South Korea',
    traitType: 'VETERAN',
  },
  {
    id: 'kr_2',
    name: 'Kim Min-jae',
    ovr: 85,
    pos: 'Defender',
    country: 'South Korea',
    traitType: 'VETERAN',
  },
  {
    id: 'kr_3',
    name: 'Jens Castrop',
    ovr: 75,
    pos: 'Defender',
    country: 'South Korea',
    traitType: 'CATALYST',
  },
  {
    id: 'kr_4',
    name: 'Lee Han-beom',
    ovr: 75,
    pos: 'Defender',
    country: 'South Korea',
    traitType: 'WONDERKID',
  },
  {
    id: 'kr_5',
    name: 'Lee Jae-sung',
    ovr: 77,
    pos: 'Midfielder',
    country: 'South Korea',
    traitType: 'WILDCARD',
  },
  {
    id: 'kr_6',
    name: 'Hwang In-beom',
    ovr: 77,
    pos: 'Midfielder',
    country: 'South Korea',
    traitType: 'CATALYST',
  },
  {
    id: 'kr_7',
    name: 'Lee Kang-in',
    ovr: 83,
    pos: 'Midfielder',
    country: 'South Korea',
    traitType: 'WONDERKID',
  },
  {
    id: 'kr_8',
    name: 'Son Heung-min',
    ovr: 85,
    pos: 'Forward',
    country: 'South Korea',
    traitType: 'WILDCARD',
  },
  {
    id: 'kr_9',
    name: 'Hwang Hee-chan',
    ovr: 75,
    pos: 'Forward',
    country: 'South Korea',
    traitType: 'VETERAN',
  },
  {
    id: 'kr_10',
    name: 'Oh Hyeon-gyu',
    ovr: 75,
    pos: 'Forward',
    country: 'South Korea',
    traitType: 'WONDERKID',
  },
];
